Add dynamic exclude product in admin page
code-rhapsodie/SyliusExtendedElasticsearchPlugin pull request #10
Opened 2020-12-11 16:15 UTC by mdavid1297

Add dynamic exclude product attributes and options in admin page
Add new Menu(Extended Search) with 2 SubMenus

2021-01-04 09:51 UTC, jbcr requested changes

2021-01-04 09:51 UTC, jbcr commented on src/Resources/config/grid/grid_exclude_attribute.yaml
> +#                id:
To delete

2021-01-04 09:51 UTC, jbcr commented on src/Resources/config/grid/grid_exclude_attribute.yaml
> +#                configuration:
To delete

2021-01-04 09:56 UTC, jbcr requested changes

2021-01-04 09:56 UTC, jbcr commented on src/Resources/config/grid/grid_exclude_attribute.yaml
> +                    class: App\Entity\Product\ProductAttribute
Replace this value with the Sylius product attribute property

2021-01-04 09:56 UTC, jbcr commented on src/Resources/config/grid/grid_exclude_option.yaml
> +                    class: App\Entity\Product\ProductOption
Replace this value with the Sylius product option property

2021-01-06 13:22 UTC, jbcr commented on README.md
> +### Exclude attributes and options dynamically from the search filter
```suggestion
### Exclude attributes and options dynamically from the search filter

To allow dynamic exclusion of product attributes (or product options), the `App\Entity\Product\ProductAttribute` class must be implement the `CodeRhapsodie\SyliusExtendedElasticsearchPlugin\Finder\FinderExcludable` interface

For example:

```php
<?php
//...
use CodeRhapsodie\SyliusExtendedElasticsearchPlugin\Finder\FinderExcludable

class ProductAttribute implements FinderExcludable
{
//...
}
```

If it's not the case(`ProductAttribute` doesn't implement `FinderExcludable`), the product attribute exclusion menu list will not be visible and will not appear.

It works the same way to allow the dynamic exclusion of `ProductOption`.
```

2021-01-06 13:23 UTC, jbcr commented on src/Controller/ProductAttributeController.php
> +     * @Route("/admin/search/excluded-attributes/toggle/{id}", name="cr_sylius_extended_elasticsearch_plugin_admin_exclude_attribute_toggle")
To delete, the routing configuration is in YAML file.

2021-01-06 13:23 UTC, jbcr commented on src/Controller/ProductOptionController.php
> +     * @Route("/admin/search/excluded-options/toggle/{id}", name="cr_sylius_extended_elasticsearch_plugin_admin_exclude_option_toggle")
To delete

2021-01-06 13:25 UTC, jbcr commented on src/Resources/config/routing.yml
> +    path: /admin/search/exclude-attributes
```suggestion
    path: '/%sylius_admin.path_name%/search/exclude-attributes'
```

2021-01-06 13:26 UTC, jbcr requested changes

2021-01-06 13:26 UTC, jbcr commented on src/Resources/config/routing.yml
> +    path: /admin/search/excluded-attributes/toggle/{id}
```suggestion
    path: '/%sylius_admin.path_name%/search/excluded-attributes/toggle/{id}'
```

2021-01-06 13:26 UTC, jbcr commented on src/Resources/config/routing.yml
> +    path: /admin/search/exclude-options
```suggestion
    path: '/%sylius_admin.path_name%/search/exclude-options'
```

2021-01-06 13:26 UTC, jbcr commented on src/Resources/config/routing.yml
> +    path: /admin/search/excluded-options/toggle/{id}
```suggestion
    path: '/%sylius_admin.path_name%/search/excluded-options/toggle/{id}'
```

2021-01-07 08:35 UTC, jeremycr commented on README.md
> +
Maybe add the same code example as above ?

2021-01-11 10:22 UTC, merged